/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/renderer/src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: {
          deep: '#0A0A14',
          base: '#0F0F1A',
          card: '#1A1A2E',
          hover: '#222238',
          border: '#2D2D4E',
        },
        primary: {
          DEFAULT: '#7C3AED',
          light: '#8B5CF6',
          dark: '#6D28D9',
          muted: '#3D1F78',
        },
        accent: {
          pink: '#EC4899',
          amber: '#F59E0B',
          green: '#10B981',
          red: '#EF4444',
          blue: '#3B82F6',
        },
        text: {
          primary: '#E2E8F0',
          secondary: '#94A3B8',
          muted: '#475569',
        },
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Consolas', 'monospace'],
      },
      animation: {
        'pet-idle':        'petIdle 3.5s ease-in-out infinite',
        'pet-happy':       'petHappy 0.9s ease-in-out infinite',
        'pet-excited':     'petExcited 0.55s ease-in-out infinite',
        'pet-tired':       'petTired 5s ease-in-out infinite',
        'pet-sad':         'petSad 3s ease-in-out infinite',
        'pet-focused':     'petFocused 5s ease-in-out infinite',
        'pet-celebrating': 'petCelebrating 0.5s ease-in-out infinite',
        'pet-dancing':     'petDancing 0.7s ease-in-out infinite',
        'fade-in': 'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
      },
      keyframes: {
        petIdle: {
          '0%, 100%': { transform: 'translateY(0px) rotate(0deg)' },
          '30%':  { transform: 'translateY(-7px) rotate(-1.5deg)' },
          '60%':  { transform: 'translateY(-10px) rotate(1deg)' },
          '80%':  { transform: 'translateY(-5px) rotate(-0.5deg)' },
        },
        petHappy: {
          '0%':   { transform: 'translateY(0px) scale(1) rotate(0deg)' },
          '20%':  { transform: 'translateY(-22px) scale(1.06) rotate(-4deg)' },
          '35%':  { transform: 'translateY(-8px) scale(0.97) rotate(3deg)' },
          '55%':  { transform: 'translateY(-20px) scale(1.05) rotate(-2deg)' },
          '70%':  { transform: 'translateY(-5px) scale(0.99) rotate(1deg)' },
          '85%':  { transform: 'translateY(-14px) scale(1.03) rotate(-1deg)' },
          '100%': { transform: 'translateY(0px) scale(1) rotate(0deg)' },
        },
        petExcited: {
          '0%':   { transform: 'translateY(0) rotate(0deg) scale(1)' },
          '20%':  { transform: 'translateY(-28px) rotate(-12deg) scale(1.08)' },
          '40%':  { transform: 'translateY(-32px) rotate(12deg) scale(1.1)' },
          '60%':  { transform: 'translateY(-24px) rotate(-8deg) scale(1.07)' },
          '80%':  { transform: 'translateY(-10px) rotate(5deg) scale(1.03)' },
          '100%': { transform: 'translateY(0) rotate(0deg) scale(1)' },
        },
        petTired: {
          '0%, 100%': { transform: 'translateY(0px) rotate(-1deg)' },
          '30%':  { transform: 'translateY(3px) rotate(-4.5deg)' },
          '60%':  { transform: 'translateY(5px) rotate(-6deg)' },
          '80%':  { transform: 'translateY(3px) rotate(-4deg)' },
        },
        petSad: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px) rotate(0deg)' },
          '20%':  { transform: 'translateY(2px) translateX(-6px) rotate(-2deg)' },
          '40%':  { transform: 'translateY(4px) translateX(-3px) rotate(-1deg)' },
          '60%':  { transform: 'translateY(2px) translateX(3px) rotate(1deg)' },
          '80%':  { transform: 'translateY(4px) translateX(6px) rotate(2deg)' },
        },
        petFocused: {
          '0%, 100%': { transform: 'scale(1) translateY(0px)' },
          '25%': { transform: 'scale(1.015) translateY(-2px)' },
          '50%': { transform: 'scale(1.025) translateY(-4px)' },
          '75%': { transform: 'scale(1.015) translateY(-2px)' },
        },
        petCelebrating: {
          '0%':   { transform: 'translateY(0px) scale(1) rotate(0deg)' },
          '20%':  { transform: 'translateY(-35px) scale(1.12) rotate(-12deg)' },
          '40%':  { transform: 'translateY(-28px) scale(1.09) rotate(12deg)' },
          '60%':  { transform: 'translateY(-20px) scale(1.06) rotate(-8deg)' },
          '80%':  { transform: 'translateY(-8px) scale(1.02) rotate(4deg)' },
          '100%': { transform: 'translateY(0px) scale(1) rotate(0deg)' },
        },
        petDancing: {
          '0%':   { transform: 'translateY(0px)   rotate(0deg)   scale(1)' },
          '10%':  { transform: 'translateY(-14px) rotate(-10deg) scale(1.05)' },
          '22%':  { transform: 'translateY(-5px)  rotate(10deg)  scale(0.97)' },
          '34%':  { transform: 'translateY(-18px) rotate(-8deg)  scale(1.07)' },
          '46%':  { transform: 'translateY(-4px)  rotate(12deg)  scale(0.96)' },
          '58%':  { transform: 'translateY(-20px) rotate(-12deg) scale(1.08)' },
          '70%':  { transform: 'translateY(-6px)  rotate(9deg)   scale(0.98)' },
          '82%':  { transform: 'translateY(-15px) rotate(-6deg)  scale(1.05)' },
          '92%':  { transform: 'translateY(-8px)  rotate(5deg)   scale(1.02)' },
          '100%': { transform: 'translateY(0px)   rotate(0deg)   scale(1)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
      },
    },
  },
  plugins: [],
}
